# Generated by Django 5.2.15 on 2026-06-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('X-RAY', 'X-RAY Framework - Investigation & Diagnosis'), ('CCTS', 'CCTS - Measure & Monetize'), ('TAX', 'Tax Planning & Audit'), ('GST', 'GST Advisory & ITC'), ('BUSINESS', 'Business Advisory & Growth'), ('OTHER', 'Other Financial Services')], default='X-RAY', max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('TAX', 'Tax Planning'), ('GST', 'GST'), ('BIZ', 'Business Advisory'), ('LAW', 'Compliance')], default='TAX', max_length=50)),
                ('published_date', models.DateField()),
                ('summary', models.TextField()),
                ('read_more_link', models.CharField(default='#', max_length=250)),
                ('image_filename', models.CharField(max_length=100)),
            ],
        ),
    ]
