# Generated by Django 5.2.15 on 2026-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AALabelCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='aa_labels/')),
                ('redirect_url', models.CharField(default='#', max_length=250)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which cards are displayed.')),
            ],
            options={
                'verbose_name': 'A&A Label Card',
                'verbose_name_plural': 'A&A Label Cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
