# Generated by Django 5.2.15 on 2026-06-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aalabelcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='What We Offer', max_length=120)),
                ('title', models.CharField(default='Expertise That Drives Real Results', max_length=180)),
                ('description', models.TextField(default='Comprehensive financial solutions designed to support every stage of your business journey.')),
                ('cta_text', models.CharField(default='View All Services', max_length=80)),
                ('cta_url', models.CharField(default='/services/', max_length=250)),
            ],
            options={
                'verbose_name': 'Home Service Section',
                'verbose_name_plural': 'Home Service Sections',
            },
        ),
        migrations.CreateModel(
            name='HomeServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='home_services/')),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('badge_one', models.CharField(max_length=80)),
                ('badge_two', models.CharField(max_length=80)),
                ('link_url', models.CharField(default='/services/', max_length=250)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which cards are displayed.')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='website.homeservicesection')),
            ],
            options={
                'verbose_name': 'Home Service Card',
                'verbose_name_plural': 'Home Service Cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
