# Generated by Django 5.2.15 on 2026-06-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homeservicesection_homeservicecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretitle', models.CharField(default='KNOW ME BETTER', max_length=120)),
                ('title_line_one', models.CharField(default='Experience.', max_length=120)),
                ('title_line_two', models.CharField(default='Expertise.', max_length=120)),
                ('title_highlight', models.CharField(default='Impact.', max_length=120)),
                ('description', models.TextField(default='A journey of trust, learning and leadership that has empowered businesses, inspired professionals and created lasting impact.')),
                ('image_filename', models.CharField(default='about_hero_portrait.png', max_length=120)),
                ('image_alt', models.CharField(default='CA Ashwani Tayal', max_length=180)),
            ],
            options={
                'verbose_name': 'About Hero Section',
                'verbose_name_plural': 'About Hero Section',
            },
        ),
        migrations.CreateModel(
            name='AboutHeroPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('icon_name', models.CharField(max_length=50)),
                ('tone', models.CharField(choices=[('navy', 'Navy'), ('blue', 'Blue'), ('midblue', 'Mid Blue'), ('gold', 'Gold'), ('lightgold', 'Light Gold')], default='navy', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='website.aboutherosection')),
            ],
            options={
                'verbose_name': 'About Hero Panel',
                'verbose_name_plural': 'About Hero Panels',
                'ordering': ['order', 'id'],
            },
        ),
    ]
