# Generated by Django 5.2.15 on 2026-06-25 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_aboutherosection_aboutheropanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(default='about', max_length=50)),
                ('pretitle', models.CharField(default='Know Me Better', max_length=120)),
                ('title', models.CharField(default='CA Ashwani Tayal', max_length=120)),
                ('description', models.TextField(default='A seasoned Chartered Accountant with over 25 years of experience, CA Ashwani Tayal has been the trusted financial backbone for hundreds of businesses across India. Known for his practical approach, depth of knowledge, and commitment to client success, he brings clarity to complexity.')),
                ('poster_filename', models.CharField(default='figma_ashwani_video_poster.png', max_length=120)),
                ('poster_alt', models.CharField(default='CA Ashwani Tayal video introduction', max_length=180)),
                ('cta_url', models.CharField(default='#appointments', max_length=250)),
            ],
            options={
                'verbose_name': 'About Intro Section',
                'verbose_name_plural': 'About Intro Sections',
            },
        ),
        migrations.CreateModel(
            name='AboutIntroFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon_name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.aboutintrosection')),
            ],
            options={
                'verbose_name': 'About Intro Feature',
                'verbose_name_plural': 'About Intro Features',
                'ordering': ['order', 'id'],
            },
        ),
    ]
