# Generated by Copilot on 2026-06-26

from django.db import migrations, models


def populate_service_details(apps, schema_editor):
    HomeServiceCard = apps.get_model("website", "HomeServiceCard")

    detail_data = {
        "Tax Planning": {
            "slug": "tax-planning",
            "detail_kicker": "Direct Tax Advisory",
            "detail_heading": "Tax Planning That Protects Cash Flow",
            "detail_intro": "Income-tax planning for individuals, HUFs, business owners, and companies with a focus on compliant savings and audit-ready documentation.",
            "detail_body": "We review your income streams, entity structure, deductions, investments, and compliance calendar to build a clear tax strategy before deadlines become pressure points.",
            "detail_points": "Personal and corporate tax optimisation\nAdvance tax and TDS planning\nCapital gains and transaction structuring\nAssessment and notice response support",
        },
        "Audit & Assurance": {
            "slug": "audit-assurance",
            "detail_kicker": "Audit Readiness",
            "detail_heading": "Assurance Built On Evidence",
            "detail_intro": "Statutory, internal, and forensic audit support for businesses that need reliable books, strong controls, and confidence in reporting.",
            "detail_body": "Our audit approach combines transaction-level review with practical control recommendations so leadership receives both compliance coverage and decision-useful insights.",
            "detail_points": "Statutory and tax audit coordination\nInternal control review\nForensic and transaction checks\nManagement reporting and remediation plans",
        },
        "Business Advisory (Design Your Business)": {
            "slug": "business-advisory",
            "detail_kicker": "Business Structuring",
            "detail_heading": "Design Your Business For Scale",
            "detail_intro": "Strategic advisory for owners navigating growth, restructuring, acquisitions, succession, or sharper operating discipline.",
            "detail_body": "We help translate business goals into entity structures, governance routines, financial controls, and measurable action plans.",
            "detail_points": "Entity and ownership structuring\nMergers, acquisitions, and restructuring support\nBusiness model and process review\nGrowth planning with financial guardrails",
        },
        "GST Consultancy": {
            "slug": "gst-consultancy",
            "detail_kicker": "Indirect Tax",
            "detail_heading": "GST Clarity From Filing To Disputes",
            "detail_intro": "End-to-end GST advisory for registration, returns, input tax credit review, reconciliations, and complex dispute resolution.",
            "detail_body": "We identify leakage, mismatch exposure, documentation gaps, and compliance risks before they become notices or blocked credits.",
            "detail_points": "GST registration and return review\nInput tax credit reconciliation\nE-way bill and invoicing controls\nDepartment notice and dispute support",
        },
        "Corporate Compliance": {
            "slug": "corporate-compliance",
            "detail_kicker": "Governance & ROC",
            "detail_heading": "Corporate Compliance Without Last-Minute Risk",
            "detail_intro": "Company law, ROC, FEMA, and secretarial compliance support for startups, SMEs, and growing corporates.",
            "detail_body": "We maintain a proactive compliance rhythm so statutory filings, board records, and governance documents stay current and investor-ready.",
            "detail_points": "ROC forms and annual filings\nBoard and shareholder documentation\nFEMA and regulatory coordination\nCompliance calendar and governance reviews",
        },
        "Financial Strategy": {
            "slug": "financial-strategy",
            "detail_kicker": "CFO Advisory",
            "detail_heading": "Financial Strategy For Better Decisions",
            "detail_intro": "CFO advisory, fundraising support, forecasting, and long-term financial structuring for businesses preparing for their next stage.",
            "detail_body": "We help leaders understand runway, margins, capital requirements, funding options, and board-level reporting so finance becomes a growth engine.",
            "detail_points": "Virtual CFO and MIS setup\nForecasting and cash-flow planning\nFundraising and lender readiness\nPricing, margin, and unit-economics review",
        },
    }

    for card in HomeServiceCard.objects.all():
        details = detail_data.get(card.title, {})
        if details:
            for field, value in details.items():
                setattr(card, field, value)
        elif not card.slug:
            card.slug = card.title.lower().replace("&", "and").replace(" ", "-")
        if not card.detail_heading:
            card.detail_heading = card.title
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_aboutintrosection_aboutintrofeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeservicecard",
            name="slug",
            field=models.SlugField(blank=True, max_length=170, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="homeservicecard",
            name="detail_kicker",
            field=models.CharField(default="Strategic Advisory", max_length=120),
        ),
        migrations.AddField(
            model_name="homeservicecard",
            name="detail_heading",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="homeservicecard",
            name="detail_intro",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homeservicecard",
            name="detail_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homeservicecard",
            name="detail_points",
            field=models.TextField(blank=True, help_text="One service-detail bullet per line."),
        ),
        migrations.RunPython(populate_service_details, migrations.RunPython.noop),
    ]
