# Generated by Django 5.2.15 on 2026-06-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_homeservicecard_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='about_certifications/')),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Certification',
                'verbose_name_plural': 'About Certifications',
                'ordering': ['order', 'id'],
            },
        ),
    ]
