# Generated by Django 5.2.15 on 2026-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_aboutcertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(upload_to='testimonial_videos/')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=180)),
                ('youtube_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial Video',
                'verbose_name_plural': 'Testimonial Videos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
