# Generated by Django 5.2.15 on 2026-06-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_testimonialvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='awards/')),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CCTSServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='CCTS Services', max_length=120)),
                ('title', models.CharField(default='Explore CCTS From Every Angle', max_length=180)),
                ('description', models.TextField(default="Curated insights and practical frameworks for every stakeholder in India's carbon market.")),
            ],
            options={
                'verbose_name': 'CCTS Service Section',
                'verbose_name_plural': 'CCTS Service Sections',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('HOME', 'Home'), ('CCTS', 'CCTS'), ('GENERAL', 'General')], default='CCTS', max_length=20)),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeaturedServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Home Featured Services', max_length=150)),
            ],
            options={
                'verbose_name': 'Home Featured Service Section',
                'verbose_name_plural': 'Home Featured Service Sections',
            },
        ),
        migrations.CreateModel(
            name='MomentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='moments_milestones/')),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('is_tall', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Moment & Milestone',
                'verbose_name_plural': 'Moments & Milestones',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Linktree', max_length=80)),
                ('url', models.URLField(default='https://linktr.ee/ca_ashwanitayal', max_length=500)),
                ('icon_name', models.CharField(default='link', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='insight',
            name='category',
            field=models.CharField(choices=[('TAX', 'Tax Planning'), ('GST', 'GST'), ('BIZ', 'Business Advisory'), ('LAW', 'Compliance'), ('CCTS', 'CCTS')], default='TAX', max_length=50),
        ),
        migrations.CreateModel(
            name='CCTSServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=10)),
                ('audience', models.CharField(max_length=180)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='ccts_services/')),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('cta_text', models.CharField(default='Learn More', max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='website.cctsservicesection')),
            ],
            options={
                'verbose_name': 'CCTS Service Card',
                'verbose_name_plural': 'CCTS Service Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeaturedServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='home_featured_services/')),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('cta_url', models.CharField(default='/services/', max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='website.homefeaturedservicesection')),
            ],
            options={
                'verbose_name': 'Home Featured Service Card',
                'verbose_name_plural': 'Home Featured Service Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetailHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='service_hero_slides/')),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='website.homeservicecard')),
            ],
            options={
                'verbose_name': 'Service Detail Hero Slide',
                'verbose_name_plural': 'Service Detail Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
