# Generated by Django 5.2.15 on 2026-09-07 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_award_cctsservicesection_faq_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-published_date', '-id'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.RemoveField(
            model_name='insight',
            name='read_more_link',
        ),
        migrations.AddField(
            model_name='insight',
            name='author_name',
            field=models.CharField(default='CA Ashwani Tayal', max_length=120),
        ),
        migrations.AddField(
            model_name='insight',
            name='body',
            field=models.TextField(blank=True, help_text="Full article content shown on the post's own page. Falls back to the summary if left empty."),
        ),
        migrations.AddField(
            model_name='insight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insight',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Cover image for the post. If left empty, a default image is used.', upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='insight',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to save this post as a draft without publishing it live.'),
        ),
        migrations.AddField(
            model_name='insight',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description for search engines. Defaults to the summary if left blank.', max_length=300),
        ),
        migrations.AddField(
            model_name='insight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='image_filename',
            field=models.CharField(blank=True, default='', help_text='Legacy: filename under static/images/, used only if no featured image is uploaded above.', max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='summary',
            field=models.TextField(help_text='Short excerpt shown on blog listing cards.'),
        ),
    ]
